@Library('Jenkins-Shared-Library-env-02') _

pipeline {
    agent any

    options { 
        skipDefaultCheckout true 
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        timestamps() 
        ansiColor('xterm')                                  // plugin: "AnsiColor"
    }

    environment {
                      // ## Project Variables ##
     PROJECT_NAME              = "myapp"                    // required
     PROJECT_KEY               = "myapp"                    // required
     COMPONENT                 = "backend"                  // required
        
                      // ## Git Variables ## 
     MY_GIT_URL                = "https://github.com/vaheedgithubac/DevOps-Project-Two-Tier-Flask-App.git"
     MY_GIT_REPO_TYPE          = "public"                   // required (public or private)
     MY_GIT_CREDENTIALS_ID     = ""                         // required for private repos
     MY_GIT_BRANCH             = ""                         // Defaults to "main" if not set
     MY_GIT_LATEST_COMMIT_ID   = get_latest_short_commit()  // <-- calls call() from shared library

                      // ## Jacoco Variables ## 
     JACOCO_GROUPID            = "org.jacoco"               // required
     JACOCO_ARTIFACT_ID        = "jacoco-maven-plugin"      // required
     JACOCO_VERSION            = "0.8.7"                    // required
     JACOCO_GOAL               = "prepare-agent"            // required

                      // ## Maven Variables ##
     MAVEN_SKIP_TESTS          = "true"                     // Defaults to 'true'
     MAVEN_GOALS               = "clean package"            // Defaults to 'clean package'

                      // Sonarqube Variables //
     SONARQUBEAPI              = "sonarqube-server"         // Must be set in (Manage Jenkins --> System)
     SCANNER_HOME              = tool 'sonarscanner'        // Must be set in (Manage Jenkins --> Tools)
     TIMEOUT_MINUTES           = 10                         // For Sonarqube Quality gate

                      // ## Docker Hub Registry Variables ##
     DOCKER_REPO_URI           = "docker.io"                // Defaults to 'docker.io'
     DOCKER_HUB_CREDENTIALS_ID = "docker-prod-creds"

                      // ## ECR Variables ##
     AWS_ACCOUNT_ID            = ""                         // required
     REGION                    = "ap-south-1"               // Defaults to 'ap-south-1'
     ECR_REPO_URI              = "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
     AWS_CREDENTIALS_ID        = "aws-prod-creds"
                              
                      // ## Trivy FS Variables ##  
     MODE                      = "fs"                       // fs --- file system 
     TARGET                    = "."                        // Defaults to "." current directory
     OUTPUT_REPORT_FORMAT      = "table"                    // table/json/sarif/yaml

                      // ## Trivy IMAGE Variables ##  
     MODE                      = "image"                    // image scan
     TARGET                    = "${PROJECT_NAME}-${COMPONENT}:${MY_GIT_LATEST_COMMIT_ID}"     // Can be set in stage
     OUTPUT_REPORT_FORMAT      = "table"                    // table/json/sarif/yaml
        
                      // ## Email Variables ##
     FROM_MAIL     = ""                                     // required
     TO_MAIL       = ""                                     // required
     REPLY_TO_MAIL = ""                                     // required
     CC_MAIL       = ""                                     // Defaults to null
     BCC_MAIL      = ""                                     // Defaults to null
     ATTACHMENTS   = ""                                     // Defaults to null  ("trivy-reports/*, owasp-reports/*, surefire-reports/*.xml")
    }

    stages {
        stage ("PRINT LATEST COMMIT ID") { steps { script { echo "Latest Commit ID: ${env.MY_GIT_LATEST_COMMIT_ID}" } } } 

        stage ("GIT CHECKOUT") { steps { script { git_checkout() } } }

        stage ("JACOCO CODE COVERAGE") { steps { script { jacoco_code_coverage() } } }

        stage ("TRIVY - FILE SYSTEM SCAN") { steps { script { trivy_scan() } } }

        stage ("SONARQUBE SCAN") { steps { script { sonarqubeScan() } } }

        stage ("SONARQUBE QUALITY GATE") { steps { script { sonarqubeQualityGate() } } }

        stage ("DOCKER IMAGE BUILD") { steps { script{ dockerImageBuild() } } }

        stage ("TRIVY - IMAGE SCAN") { steps { script { trivy_scan() } } }

        stage ("DOCKER HUB PUSH") { steps { script { dockerPush() } } }

        stage ("ECR PUSH") { steps { script { ecrPush() } } }
    }
    post { always { script { sendEmail() } } }
}
